version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Substitute with your application base image
    steps:
      - checkout
      
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      
      - run:
          name: Run Tests
          command: |
            pytest tests/
    
      - run:
          name: Snyk Security Scan
          command: |
            curl -sS https://get.snyk.io/cli/latest/snyk-linux > snyk && chmod +x snyk
            ./snyk test
      
      - run:
          name: Create Docker Image
          command: |
            docker build -t my-app:latest .

      - run:
          name: Push to JFrog
          command: |
            curl -u "${JFROG_USERNAME}:${JFROG_API_KEY}" -T my-app:latest "https://<your-jfrog-instance>/artifactory/<your-repository>/my-app:latest"
      
      - run:
          name: Deploy to AWS
          command: |
            aws s3 cp my-app:latest s3://<your-s3-bucket>/<path>/
    
      - run:
          name: Notify Dynatrace Deployment
          command: |
            curl -X POST "https://<your-dynatrace-environment-id>.live.dynatrace.com/api/v2/deployment/notifications" \
            -H "Authorization: Api-Token ${DYNATRACE_API_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{
                  "deploymentName": "CircleCI Deploy",
                  "version": "1.0.0",
                  "source": {"type": "CI", "name": "CircleCI"},
                  "artifacts": {"url": "https://example.com/my-artifact-url"}
                }'

      - run:
          name: Create Jira Ticket
          command: |
            curl -X POST -H "Content-Type: application/json" \
            --user ${JIRA_USERNAME}:${JIRA_API_TOKEN} \
            --data '{
              "fields": {
                "project": {
                  "key": "<YOUR_JIRA_PROJECT_KEY>"
                },
                "summary": "New Deployment to AWS",
                "description": "Deployed version 1.0.0 to AWS.",
                "issuetype": {
                  "name": "Task"
                }
              }
            }' "https://<your-jira-instance>.atlassian.net/rest/api/3/issue/"
    
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
